### ISSUE TITLE
Nodemailer

### ISSUE THREAD

**Issue by PavingPlus** [PavingPlus/paving-plus-newsite#8]
How to add node Nodemailer in app.js

**Comment by ashish13377** [comment]
First, you need to install "Node Mailer"

then add this to your app.js

app.post("/contact/send-mail", (req, res) => {
    const { fullName, email, phone, message } = req.body;

    const output = `
            <h4> Contact us for detail. </h4>
            <br />
            <p><strong>Name : </strong> ${fullName}</p>
            <p><strong>Email : </strong> ${email}</p>
            <p><strong>Phone : </strong> ${phone}</p>
            <p><strong>Message : </strong> ${message}</p>
            <br />
            <br />
            <p>Thank you</p>
           `


    let transporter = nodemailer.createTransport({
        host: "smtp.gmail.com",
        port: 587,
        secure: false, // true for 465, false for other ports
        auth: {
            user: "", // generated ethereal user
            pass: "", // generated ethereal password
        },
    });

    let mailOption = {
        from: '', // sender address
        to: '', // list of receivers
        subject: "", // Subject line
        text: "", // plain text body
        html: output, // HTML body
    }

    // send mail with defined transport object
    transporter.sendMail(mailOption, (error, info) => {
        if (error) {
            res.json(error)
        } else {
            const data = info.messageId;
            res.json({ message: "Message sent", data })
        }
    });

})
